/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'timbo' at '15/07/17 15:07' with Gradle 3.2.1
 *
 * @author timbo, @date 15/07/17 15:07
 */
public class Demo {
    public static void main(String[] args) {

        System.out.println("JChem version: ?");

    }
}
